### PR TITLE
[GITHUB-4] Fix removal of the anonymous user

### PR DESCRIPTION
**Pull request by wojtek-oledzki**

### CODE REVIEW

**Comment by wojtek-oledzki** [comment]
@lobsterdore can you take a quick look pls

**Comment by lobsterdore** [comment]
@wojtek-oledzki Hello stranger :)

When are you seeing this issue? I haven't encountered a situation where I need become: yes on the anon user removal.

**Comment by wojtek-oledzki** [comment]
@lobsterdore try on a system where you don't have root.

```
TASK [sansible.mysql : Remove anonymous user] **********************************
fatal: [***]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database, check login_user and login_password are correct or /home/ubuntu/.my.cnf has the credentials. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")"}
```

this is the first pass on plain Xenial server. The `become: yes` is not proper solution anyway - it only works if the `mysql.root_login` is set to `root`

**Comment by wojtek-oledzki** [comment]
@lobsterdore let me have a quick check - I will ensure the "root" user + passwd first and then remove the anonymous user...

**Comment by wojtek-oledzki** [comment]
@lobsterdore works, take a look again.

**Comment by lobsterdore** [comment]
LGTM 👍 

Closes #4

**Review by lobsterdore — APPROVED** [review]

**Pull request merged**
